
name: demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # The git history is needed for good evaluation of Pull Request commit messages.
          # By default this action checkout only last commit.
          # For PR it's temporary merge commit to current master and orginal commit message is missing.
          # For big projects can be set to 1000 for performance reasons.
          fetch-depth: "0"
      - uses: mstachniuk/ci-skip@v1 # If the commit message (or a merge message) contains [ci skip] (in subject of body) the action will stop
        with:
          fail-fast: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Create an .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_VUE_APP_HERE_API_KEY: ${{ secrets.HERE_API_KEY }}
          file_name: .env

      - name: Generate static demo app
        run: npm run build

      - name: Deploy to github pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: demo
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}